FROM caddy:2.6.2-builder-alpine AS caddybuild

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

# ---- Dependencies ----
FROM node:16-alpine AS webbuild

WORKDIR /app

COPY package.json ./
COPY . /app

RUN yarn install && \
    yarn build

FROM caddy:2.6.2-alpine

COPY --from=caddybuild /usr/bin/caddy /usr/bin/caddy
COPY --from=webbuild /app/dist /srv
